/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-03-20 16:41:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<Html>  \r\n");
      out.write("<head>   \r\n");
      out.write("<title>  Update your details \r\n");
      out.write("</title>  \r\n");
      out.write("</head>  \r\n");
      out.write("<body bgcolor=\"Lightskyblue\">  \r\n");
      out.write("<br>  \r\n");
      out.write("<br>  \r\n");
      out.write("<form action=\"Connect.jsp\" method=\"post\">\r\n");
      out.write("    <label> Enter Username: </label>         \r\n");
      out.write("	<input type=\"text\" name=\"uname\" size=\"15\"/> <br> <br>   \r\n");
      out.write("	<label> Enter Password: </label>         \r\n");
      out.write("	<input type=\"text\" name=\"password\" size=\"15\"/> <br> <br> \r\n");
      out.write("	<label> Firstname: </label>         \r\n");
      out.write("	<input type=\"text\" name=\"firstname\" size=\"15\"/> <br> <br>   \r\n");
      out.write("	<label> Lastname: </label>         \r\n");
      out.write("	<input type=\"text\" name=\"lastname\" size=\"15\"/> <br> <br> \r\n");
      out.write("	<label> Age: </label>         \r\n");
      out.write("	<input type=\"text\" name=\"age\" size=\"15\"/> <br> <br><br>\r\n");
      out.write("    Enter Weight:<input type=\"text\" name=\"w\" size=\"15\"/> <br> <br>  \r\n");
      out.write("	<label>   \r\n");
      out.write("	Blood Group :  \r\n");
      out.write("	</label>   \r\n");
      out.write("	<select name=\"bloodgroup\">  \r\n");
      out.write("	<option value=\"o+\">o+</option>  \r\n");
      out.write("	<option value=\"o-\">o-</option>  \r\n");
      out.write("	<option value=\"A+\">A+</option>  \r\n");
      out.write("	<option value=\"A-\">A-</option>  \r\n");
      out.write("	<option value=\"B+\">B+</option>  \r\n");
      out.write("	<option value=\"B-\">B-</option>  \r\n");
      out.write("	<option value=\"AB-\">AB-</option>  \r\n");
      out.write("	<option value=\"AB+\">AB+</option>  \r\n");
      out.write("	</select>  \r\n");
      out.write("	<br>  \r\n");
      out.write("	<br>  \r\n");
      out.write("	<label>   \r\n");
      out.write("	Gender :  \r\n");
      out.write("	</label><br>  \r\n");
      out.write("	<input type=\"radio\" name=\"gender\" value=\"male\"/> Male <br>  \r\n");
      out.write("	<input type=\"radio\" name=\"gender\" value=\"female\"/> Female <br>  \r\n");
      out.write("	<input type=\"radio\" name=\"gender\" value=\"other\"/> Other  \r\n");
      out.write("	<br>  \r\n");
      out.write("	<br>  \r\n");
      out.write("	  \r\n");
      out.write("	<label>   \r\n");
      out.write("	Phone :  \r\n");
      out.write("	</label>  \r\n");
      out.write("	<input type=\"text\" name=\"country code\"  value=\"+91\" size=\"2\"/>   \r\n");
      out.write("	<input type=\"text\" name=\"phone\" size=\"10\"/> <br> <br>  \r\n");
      out.write("	Address  \r\n");
      out.write("	<input type=\"text\" name=\"address\"><br>\r\n");
      out.write("	<br>\r\n");
      out.write("	Email:  \r\n");
      out.write("	<input type=\"email\" id=\"email\" name=\"email\"/> <br>    \r\n");
      out.write("	</br>\r\n");
      out.write("	Donated Blood Recently(Below 7 months span):<br>\r\n");
      out.write("	<input type=\"radio\" name=\"blood\" value=\"YES\"/> YES<br>  \r\n");
      out.write("	<input type=\"radio\" name=\"blood\" value=\"NO\"/> NO <br> <br>\r\n");
      out.write("	</br>\r\n");
      out.write("	<input type=\"submit\" value=\"Submit\">  \r\n");
      out.write("</form>  \r\n");
      out.write("</body>  \r\n");
      out.write("</html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
